# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes
  DEEP_LINK_HOST: WillowCreekApp
  ROOT_API_URL: ${ROOT_URL}
UNIVERSAL_LINKS:
  APPLE_APP_ID: com.customchurchapps.appc2cui2f7
  APPLE_TEAM_ID: HBXNNZ69FP
  APP_STORE_LINK: https://apps.apple.com/us/app/willow-creek-church-app/id1447664228
  GOOGLE_APP_ID: com.willowcreekapp
  GOOGLE_KEYSTORE_SHA256: 56:32:BF:42:A3:4D:33:AC:14:36:FC:E5:C4:93:6B:49:6E:C9:8B:E2:01:A0:9A:2A:B9:8E:A0:15:F4:EA:89:69
  PLAY_STORE_LINK: https://play.google.com/store/apps/details?id=com.willowcreekapp
ROCK:
  API_URL: https://rock.willowcreek.org/api
  API_TOKEN: ${ROCK_TOKEN}
  IMAGE_URL: ${ROCK_URL}/GetImage.ashx
  SHARE_URL: https://willowcreek-api.herokuapp.com
  # This should match the timezone of the Rock server
  TIMEZONE: 'America/Chicago'
  USE_PLUGIN: true
  SHOW_INACTIVE_CONTENT: ${ROCK_SHOW_INACTIVE_CONTENT}
ONE_SIGNAL:
  APP_ID: 537c4960-f27c-4a41-a57a-4471ae0228bb
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: https://apollos.churchonline.org/api/v1/
  MEDIA_URLS: []
  WEB_VIEW_URL: https://apollos.churchonline.org/
ALGOLIA:
  APPLICATION_ID: EHIORCCAE1
  API_KEY: ${ALGOLIASEARCH_API_KEY}
  # TODO: should we support multiple indices? how?
  SEARCH_INDEX: ContentItems
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
YOUTUBE:
  API_KEY: ${YOUTUBE_API_KEY}
  PLAYLIST_FOR_CAMPUS:
    DEFAULT: 'UUmFRqL-BDXeaYwMxYDfhu_w'
    # This is not a real ID ;)
    123: 'UUmFRqL-BDXeaYwMxYDfhu_w'
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
ANALYTICS:
  # Filling out these fields will automatically enable analytics tracking
  # on the accompanying service
  SEGMENT_KEY:
  GA_ID:
  USE_ROCK: false
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    NIV: '71c6eab17ae5b667-01'
CLOUDINARY:
  # Cloudinary is used to improve image loading
  # value should look something like
  # cloudinary://123123123:adkfnla_adASDv_adAS@test
  URL: ${CLOUDINARY_URL}
ENGINE:
  API_KEY: ${ENGINE_API_KEY}
  SCHEMA_TAG: ${ENGINE_SCHEMA_TAG}

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  INTERACTIONS:
    # Name of the InteractionChannel that will be created
    CHANNEL_NAME: Apollos Willow Creek App
    # Name of the InteractionComponent that will be created for Content Items
    COMPONENT_NAME: Apollos Willow Creek Item
    # 512 is "Mobile App"
    CHANNEL_MEDIUM_TYPE_ID: 512

  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: ContentChannelItem
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [6, 13]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelTypeId: [12]
    MediaContentItem:
      EntityType: ContentChannelItem
      ContentChannelTypeId: [5]
    WillowTVContentItem:
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
    WeekendContentItem:
      EntityType: ContentChannelItem
      ContentChannelId: [16]
    ContentItem:
      EntityType: ContentChannelItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 814

  # Apollos will pull these content channels and expose them in the app on the discover screen.
  DISCOVER_CONTENT_CHANNEL_IDS:
    - 17 # Sermon Series
    - 22 # Devo series
    - 14 # Worship
    - 24 # Podcast series
    - 18 # Articles
    - 20 # Note from pastor
    - 27 # Study guides
    - 19 # Church updates
    - 13 # Stories
    - 12 # Willow Creative
    - 15 # Classes

  # Apollos will pull content items from these channels and expose them on the user feed
  # However, it will not expose the channel itself.
  FEED_CONTENT_CHANNEL_IDS:
    - 20
    - 18
    - 19
    - 13
    - 14
    - 16 # Sermons
    - 21 # Devotionals

  CAMPAIGN_CHANNEL_IDS:
    - 25

  POINTER_CHANNEL_TYPE_ID: 14

  NEXT_STEPS_CONTENT_CHANNEL_ID: 26

  GROW_CAMPAIGN_CONTENT_CHANNEL_ID: 13
  MY_WILLOW_CAMPAIGN_CONTENT_CHANNEL_ID: 13

  YOUTUBE_CONTENT_CHANNEL: 12

  # Used to determine what Campus ID correseponds to what DataView.
  # We hijack the persona feature to show a campus specific user feed.
  CAMPUS_DATA_VIEWS:
    - # Chicago
      CampusDataViewGuid: 5f0f1aeb-330a-4cff-b99e-30d9f6f02c9c
      YoutubeChannelId: UCmniIV0tciTcKRTzPJsl9JA
      CampusId: 6
      # These are shown on the Connect tab.
      # Links with an icon show up in the ActionBar.
      # All other links show up as links in the "Connect" list.
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/chicago
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/pay/wcchicago
          style: EXTERNAL_BAR_ITEM
        - title: Find a serving opportunity
          url: https://www.willowcreek.org/en/serving-opportunities/chicago
        - title: Join a small group
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/chicago
        - title: I need prayer
          url: mailto:glenn@willowchicago.org
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # Casa De Luz
      CampusDataViewGuid: 9cd67fd5-f316-4fb9-99b7-ce998721558a
      YoutubeChannelId: UCmFRqL-BDXeaYwMxYDfhu_w # TODO
      CampusId: 5
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/casa-de-luz
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/pay/wccasadeluz
          style: EXTERNAL_BAR_ITEM
        - title: Join a small group
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/casa-de-luz
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # Crystal Lake
      CampusDataViewGuid: 4db5a26d-9f4d-4d24-8ec0-4ffc05809ffa
      YoutubeChannelId: UC9E9uVr2aeALkyMCC6ryErQ
      CampusId: 4
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/crystal-lake
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/pay/wccrystallake
          style: EXTERNAL_BAR_ITEM
        - title: Find a serving opportunity
          url: https://www.willowcreek.org/en/serving-opportunities/crystal-lake
        - title: Join a small group
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/crystal-lake
        - title: I need prayer
          url: mailto:wclprays@willowcreek.org
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # Huntley Campus
      CampusDataViewGuid: f28fef3a-e6d7-4837-b003-c9a1d9cd235f
      YoutubeChannelId: UCTURjBpziqKIfe3_W3ZK9QA
      CampusId: 7
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/connect/getting-started/huntley/groups
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/pay/wchuntley
          style: EXTERNAL_BAR_ITEM
        - title: Find a serving opportunity
          url: https://www.willowcreek.org/en/serving-opportunities/huntley
        - title: Join a small group
          url: https://www.willowcreek.org/connect/getting-started/huntley/groups
        - title: I need prayer
          url: mailto:hmadsen@wcservingvolunteer.org
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # North Shore
      CampusDataViewGuid: 5bb891df-f608-4a2b-948e-1537a5e6b1c6
      YoutubeChannelId: UCBwM1fD-lp0-JeNf-rGGniw
      CampusId: 3
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.northshoregroups.org/
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/pay/wcnorthshore
          style: EXTERNAL_BAR_ITEM
        - title: Join a small group
          url: https://www.northshoregroups.org/
        - title: I need prayer
          url: https://visitwillow.org/prayer
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # South Barrington
      CampusDataViewGuid: bbdfae06-5f70-4703-954c-a21d1a6b140b
      YoutubeChannelId: UCmFRqL-BDXeaYwMxYDfhu_w
      CampusId: 1
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/south-barrington
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/g/willowcreek?src=hpp
          style: EXTERNAL_BAR_ITEM
        - title: Find a serving opportunity
          url: https://www.willowcreek.org/en/serving-opportunities/south-barrington/serve-finder
        - title: Join a small group
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/south-barrington
        - title: I need prayer
          url: https://www.willowcreek.org/en/contact/prayer
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # South Lake
      CampusDataViewGuid: e3bc6b72-bc9f-4f08-8ba8-49577bb049ed
      YoutubeChannelId: UCVWoE4BvcXQ9s3k0qPJ12nQ
      CampusId: 8
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/south-lake
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: https://pushpay.com/pay/wcsouthlake
          style: EXTERNAL_BAR_ITEM
        - title: Find a serving opportunity
          url: https://www.willowcreek.org/en/serving-opportunities/south-lake
        - title: Join a small group
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/south-lake
        - title: I need prayer
          url: https://www.willowcreek.org/en/contact/prayer
        - title: Contact us
          url: https://www.willowcreek.org/en/contact
    - # Wheaton
      CampusDataViewGuid: d96b6f89-441a-489a-b8df-a406ae108474
      YoutubeChannelId: UClw5lxvIxdYq5M5y0teCCng
      CampusId: 2
      ProfileLinks:
        - title: Groups
          icon: groups
          url: https://www.willowcreek.org/en/connect/ministries/small-groups-and-section-communities/wheaton
          style: BAR_ITEM
        - title: Give
          icon: love-it-hand
          url: http://pushpay.com/pay/wcwheaton
          style: EXTERNAL_BAR_ITEM
        - title: Find a serving opportunity
          url: mailto:lmclaughlin@willowcreek.org?subject=I would like to serve!
        - title: Join a small group
          url: mailto:lmclaughlin@willowcreek.org?subject=I would like to join a small group
        - title: I need prayer
          url: mailto:prayer@willowwheaton.org?subject=I need prayer
        - title: I have a praise
          url: mailto:prayer@willowwheaton.org?subject=I have a praise
        - title: Contact us
          url: https://www.willowcreek.org/en/contact

  SERMON_CHANNEL_ID: 16

  SERVING_GROUP_TYPE_ID: 23
  COMMUNITY_GROUP_TYPE_ID: 25
  FAMILY_GROUP_TYPE_ID: 10

HOME_FEATURES:
  - title:
    subtitle: Next Steps
    algorithms:
      - type: PERSONA_FEED
        arguments:
          first: 100
          contentChannelIds:
            - 26
  - title:
    subtitle: Upcoming Services
    algorithms:
      - type: POINTER_FEED
        arguments:
          first: 100
          contentChannelIds:
            - 28
  - title:
    subtitle: Here's what's coming up!
    algorithms: [UPCOMING_EVENTS]
    additionalAction:
      title: 'See more'
      action: VISIT_ROUTE
      actionMeta: EventFeed

# Default mapping of field types -> ids. There's probably no reason to edit this.
ROCK_CONSTANTS:
  TEXT: 1
  MULTI_SELECT: 2
  BOOLEAN: 3
  COLOR: 4
  SINGLE_SELECT: 6
  INTEGER: 7
  PAGE_REFERENCE: 8
  IMAGE: 10
  DATE: 11
  DECIMAL: 14
  DEFINED_TYPE: 15
  DEFINED_VALUE: 16
  PERSON: 18
  HTML: 20
  MEMO: 21
  GROUP_TYPES: 22
  GROUP: 23
  CAMPUSES: 26
  ENTITY_TYPE: 29
  CAMPUS: 30
  EMAIL_TEMPLATE: 31
  FILE: 32
  GROUP_TYPE: 33
  KEY_VALUE_LIST: 34
  BINARY_FILE_TYPE: 35
  WORKFLOW_TYPE: 36
  BINARY_FILE: 37
  FINANCIAL_ACCOUNT: 38
  FINANCIAL_ACCOUNTS: 39
  COMPONENT: 40
  COMPONENTS: 41
  CATEGORIES: 42
  GROUP_ROLE: 43
  CATEGORY: 44
  LOCATION: 45
  DATE_RANGE: 46
  DECIMAL_RANGE: 47
  INTEGER_RANGE: 48
  TIME: 49
  GROUP_LOCATION_TYPE: 50
  CODE_EDITOR: 51
  PERSON_BADGES: 52
  SITE: 53
  COMMUNICATION_TEMPLATE: 54
  DAY_OF_WEEK: 55
  DAYS_OF_WEEK: 56
  REMOTE_AUTHS: 57
  COMPARISON: 58
  METRIC_ENTITY: 59
  WORKFLOW_ACTIVITY: 60
  WORKFLOW_ATTRIBUTE: 61
  METRICS: 62
  ENTITY: 63
  METRIC_CATEGORIES: 64
  WORKFLOW_TEXT_OR_ATTRIBUTE: 65
  SLIDING_DATE_RANGE: 66
  GROUP_TYPE_GROUP: 67
  SECURITY_ROLE: 68
  VALUE_LIST: 69
  CURRENCY: 70
  EMAIL: 71
  URL_LINK: 72
  WORKFLOW_TYPES: 73
  ATTRIBUTE: 74
  SCHEDULES: 75
  CONTENT_CHANNEL: 76
  AUDIO_FILE: 77
  AUDIO_URL: 78
  VIDEO_FILE: 79
  VIDEO_URL: 80
  ENCRYPTED_TEXT: 81
  FILTER_DATE: 82
  DATE_TIME: 83
  DEFINED_VALUE_RANGE: 84
  RATING: 85
  SYSTEM_EMAIL: 86
  FINANCIAL_GATEWAY: 87
  GROUP_AND_ROLE: 88
  NOTE_TYPE: 89
  NOTE_TYPES: 90
  EVENT_CALENDAR: 91
  EVENT_ITEM: 92
  CONNECTION_ACTIVITY_TYPE: 93
  CONNECTION_OPPORTUNITY: 94
  CONNECTION_REQUEST: 95
  CONNECTION_STATE: 96
  CONNECTION_STATUS: 97
  CONNECTION_TYPE: 98
  CONNECTION_TYPES: 99
  MERGE_TEMPLATE: 100
  RANGE_SLIDER: 101
  BINARY_FILE_TYPES: 102
  MARKDOWN: 103
  DATA_VIEW: 104
  PHONE_NUMBER: 105
  SCHEDULE: 106
  LAVA_COMMANDS: 107
  ADDRESS: 108
  BENEVOLENCE_REQUEST: 109
  CONTENT_CHANNEL_TYPES: 110
  WORKFLOW: 111
  SSN: 112
  MATRIX: 113
  LAVA: 114
  DATA_VIEWS: 115
  COMMUNICATION_PREFERENCE: 116
  INTERACTION_CHANNEL: 117
  GROUP_MEMBER: 118
  TIME_ZONE: 119
  LABEL: 120
