export default () => ({
  ContentChannelTypeId: 6,
  Name: 'My super cool content channel',
  Description: 'Some description',
  IconCssClass: 'fa fa-star',
  RequiresApproval: false,
  ItemsManuallyOrdered: false,
  ChildItemsManuallyOrdered: false,
  EnableRss: false,
  ChannelUrl: '',
  ItemUrl: '',
  TimeToLive: 0,
  ContentControlType: 0,
  RootImageDirectory: '',
  IsIndexEnabled: false,
  IsTaggingEnabled: false,
  ItemTagCategoryId: null,
  CreatedDateTime: null,
  ModifiedDateTime: '2018-01-01T01:01:01.001',
  CreatedByPersonAliasId: null,
  ModifiedByPersonAliasId: 61,
  Id: 'some-id',
  Guid: 'some-sort-of-long-guid',
  ForeignId: null,
  ForeignGuid: null,
  ForeignKey: null,
});
